
server:
  port: 8082

spring:
#  spring:
#    profiles:
#      active: dev
  application:
    name: bcp-shopvintage-auctions

  data:
    mongodb:
      host: 70.37.86.87
      port: 27016
      database: shopvintage

  cloud:
    stream:
      bindings:
        bidConsumer-in-0:
          destination: bids-queue
        auctionConsumer-in-0:
          destination: auctions-queue

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

shopvintage:
  services:
    bidders_url: http://192.168.1.6:9999



